### ISSUE TITLE
Spurious "yintercept" labels show up when using geom_hline()

### ISSUE THREAD

**Issue by adamliter** [YuLab-SMU/ggbreak#28]
When I try to use `scale_y_break` while also adding a horizontal line to a graph, spurious "yintercept" labels show up for both subplots underneath the y-axis label. Here's a hopefully reproducible example:

```r
library(ggplot2)
library(ggbreak)

data <- data.frame(x = c(1:10),
                   y = c(5:13, 100))

(plot <-  ggplot(data, aes(x = x, y = y)) +
  geom_point() +
  geom_hline(aes(yintercept = 3)) +
  scale_y_break(c(14, 95), scales = 0.2))
```

Here's the plot that I get:

![image](https://user-images.githubusercontent.com/4974404/134042573-76a3ab40-6f3f-4ac5-bc19-933391227ee9.png)

And here's the output of `sessionInfo()` if it's helpful:

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] here_1.0.1      ggbreak_0.0.5   forcats_0.5.1   stringr_1.4.0  
 [5] dplyr_1.0.7     purrr_0.3.4     readr_2.0.1     tidyr_1.1.3    
 [9] tibble_3.1.4    ggplot2_3.3.5   tidyverse_1.3.1 lmerTest_3.1-3 
[13] lme4_1.1-27.1   Matrix_1.3-4   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7          lubridate_1.7.10    lattice_0.20-44    
 [4] digest_0.6.27       rprojroot_2.0.2     assertthat_0.2.1   
 [7] utf8_1.2.2          R6_2.5.1            cellranger_1.1.0   
[10] backports_1.2.1     reprex_2.0.1        httr_1.4.2         
[13] pillar_1.6.2        yulab.utils_0.0.2   rlang_0.4.11       
[16] readxl_1.3.1        rstudioapi_0.13     minqa_1.2.4        
[19] nloptr_1.2.2.2      labeling_0.4.2      splines_4.1.1      
[22] bit_4.0.4           munsell_0.5.0       broom_0.7.9        
[25] compiler_4.1.1      numDeriv_2016.8-1.1 modelr_0.1.8       
[28] xfun_0.25           pkgconfig_2.0.3     gridGraphics_0.5-1 
[31] broom.mixed_0.2.7   tidyselect_1.1.1    fansi_0.5.0        
[34] crayon_1.4.1        tzdb_0.1.2          dbplyr_2.1.1       
[37] withr_2.4.2         MASS_7.3-54         grid_4.1.1         
[40] nlme_3.1-152        jsonlite_1.7.2      gtable_0.3.0       
[43] lifecycle_1.0.0     DBI_1.1.1           magrittr_2.0.1     
[46] scales_1.1.1        vroom_1.5.4         cli_3.0.1          
[49] stringi_1.7.4       farver_2.1.0        fs_1.5.0           
[52] xml2_1.3.2          ellipsis_0.3.2      generics_0.1.0     
[55] vctrs_0.3.8         boot_1.3-28         tools_4.1.1        
[58] bit64_4.0.5         ggplotify_0.1.0     glue_1.4.2         
[61] hms_1.1.0           parallel_4.1.1      colorspace_2.0-2   
[64] aplot_0.1.0         rvest_1.0.1         knitr_1.33         
[67] haven_2.4.3         patchwork_1.1.1
```

**Comment by GuangchuangYu** [comment]
this should be fixed in github version.

**Comment by GuangchuangYu** [comment]
@xiangpin it seems this problem still exists. pls fix it.

**Comment by xiangpin** [comment]
ok

**Comment by GuangchuangYu** [comment]
fixed by <https://github.com/YuLab-SMU/ggbreak/pull/29>.

**Comment by jordan-dinardo** [comment]
Hi. I am still having issues with "spurius y-intercept" when using ggbreak with hlines  and cannot seem to install the github version. Any guidance would be greatly appreciated. 

remotes::install_github("GuangchuangYu/ggbreak")

Error: Failed to install 'ggbreak' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`GuangchuangYu`) and repo name (`ggbreak`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

**Comment by adamliter** [comment]
This is because the repository name was changed and the instructions in the README file are outdated. Try this instead:

```
remotes::install_github("YuLab-SMU/ggbreak")
```

**Comment by jordan-dinardo** [comment]
Thanks! I was able to successfully install ggbreak package from github, but it doesn't seem to solve the "spurious y intercept" issue when using geom_hline. I've made sure to uninstall the cran version of ggbreak.

**Comment by GuangchuangYu** [comment]
Thanks @adamliter and the README issue was fixed.

@jordan-dinardo The CRAN version should not have this issue. 

1. use `packageVersion("ggbreak")` to make sure you are using the correct version. 
2. remember to restart R if you load an old version and install a new version.

**Comment by jordan-dinardo** [comment]
Unfortunately I am still receiving the error when I use the reinstalled the CRAN version and restarted R. 

![Screen Shot 2022-01-20 at 8 39 57 AM](https://user-images.githubusercontent.com/76932372/150382410-91564472-9f14-49ad-ad03-734751e70619.png)

**Comment by jordan-dinardo** [comment]
Here's some reproducible code. I realized the issue arises when the y-intercept is unique to facet variable. 

data <- data.frame(x = c(1:10),
                   y = c(5:13, 100),
                   z=rep(c(1:2),each=5),
                   yint=rep(c(5,96)),each=5)

(plot<-ggplot(data, aes(x = x, y = y)) +
    geom_bar(stat="identity",position="stack") +
    geom_hline(aes(yintercept = yint)) +
    facet_wrap(~z)+
    scale_y_break(c(14, 95), scales = 0.2))

Here's what the plot looks like.
<img width="761" alt="Screen Shot 2022-01-20 at 8 55 25 AM" src="https://user-images.githubusercontent.com/76932372/150385178-47141154-b4c3-4397-bc0f-e5347e948cbc.png">

**Comment by GuangchuangYu** [comment]
@xiangpin pls check whether it works with facet.

**Comment by GuangchuangYu** [comment]
@jordan-dinardo pls try the github version.

**Comment by jordan-dinardo** [comment]
@GuangchuangYu The issue is still present when I use the github version.

**Comment by xiangpin** [comment]
@jordan-dinardo Hello, this issue should be fixed by this [request](https://github.com/YuLab-SMU/ggbreak/pull/42). pls reinstall `ggbreak` via `remotes::install_github("YuLab-SMU/ggbreak")`, then try again.
